version: '3.8'

services:
  web-portfolio:
    image: ${DOCKER_USERNAME}/web-portfolio:latest
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - default

networks:
  portfolio-network:
    external: false