version: '3.8'

services:
  web-portfolio:
    container_name: web-portfolio
    image: ${DOCKER_USERNAME}/web-portfolio:latest
    expose:
      - "80"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true