version: '3.8'
services:
  web-portfolio:
    image: web-portfolio:latest
    expose:
      - "80"
    depends_on:
      - mail-server
    networks:
      - portfolio-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mail-server:
    image: mail-server:latest
    secrets:
      - mail_server_secret
    configs:
      - source: mail_server_config
        target: /run/config/mail_server_config
    networks:
      - portfolio-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

secrets:
  mail_server_secret:
    external: true

configs:
  mail_server_config:
    external: true

networks:
  portfolio-network:
    external: true
