version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - portfolio-network
    depends_on:
      - portfolio
      - mail-server

  web-portfolio:
    container_name: web-portfolio
    image: web-portfolio:latest
    expose:
      - "3000"
    depends_on:
      - mail-server
    networks:
      - portfolio-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mail-server:
    image: mail-server:latest
    expose:
      - "3000"
    secrets:
      - mail_server_secret
    configs:
      - source: mail_server_config
        target: /run/config/mail_server_config
    networks:
      - portfolio-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  portfolio-network:
    external: true

secrets:
  mail_server_secret:
    external: true

configs:
  mail_server_config:
    external: true