name: CI

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  validate-docker-compose:
    name: Validate Docker Compose Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo chmod +x /usr/local/bin/docker-compose

      - name: Validate Docker Compose file
        run: docker-compose -f docker-compose.yml config

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: validate-docker-compose
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          current_version=$(cat VERSION)
          previous_version=$(docker image ls --filter "reference=${{ secrets.DOCKER_USERNAME }}/web-portfolio" --format "{{.Repository}}:{{.Tag}}" | awk -F ':' '{print $2}')
          if [[ $current_version -eq $previous_version ]]; then echo 'Update semantic version in VERSION file'; exit 1; fi
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-portfolio:$current_version -t ${{ secrets.DOCKER_USERNAME }}/web-portfolio:latest .
          docker save --output portfolio-versioned.docker ${{ secrets.DOCKER_USERNAME }}/web-portfolio:$current_version
          docker save --output portfolio-latest.docker ${{ secrets.DOCKER_USERNAME }}/web-portfolio:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: portfolio-docker-images
          path: |
            portfolio-versioned.docker
            portfolio-latest.docker

  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: portfolio-docker-images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker load --input ./portfolio-versioned.docker
          docker load --input ./portfolio-latest.docker
          current_version=$(cat VERSION)
          docker push ${{ secrets.DOCKER_USERNAME }}/web-portfolio:$current_version
          docker push ${{ secrets.DOCKER_USERNAME }}/web-portfolio:latest

  deploy-docker-compose:
    name: Deploy Docker Compose
    runs-on: ubuntu-latest
    needs: push-docker-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker Compose file to remote server
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/web-portfolio/docker-compose.yml
